import type { Metadata } from "next";
import localFont from "next/font/local";
import { Playfair_Display } from "next/font/google";
import "./globals.scss";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const montserratSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-montserrat-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const geistPlayfair = localFont({
  src: "./fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf",
  variable: "--font-Playfair-Display",
  weight: "100 900",
});

const playFi = Playfair_Display({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserratSans.variable} ${geistMono.variable} ${geistSans.variable} ${geistPlayfair.variable} ${playFi.className}`}
      >
        {children}
      </body>
    </html>
  );
}
